version: '3.4'

services:

  portainer:  
    container_name: portainer  
    hostname: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:2.9.3
    ports:  
      - 9443:9443
      - 8000:8000
    volumes:
      - portainer-data-volume:/data
    networks:  
      - portainer  
  
volumes:  
  portainer-data-volume: 
    external: true